### ISSUE TITLE
Encode returning false

### ISSUE THREAD

**Issue by ajmas** [noseglid/base85#13]
I am running into an issue where base85.encode() is returning false. This is happening bother with a buffer and a text string. I am using Node 8.9.4.

For the text case:

    base85.encode('hello world')

For the buffer it is one created by crypto.cipher

    const iv = crypto.randomBytes(16);
    const cipher = crypto.createCipheriv(algorithm, key, iv);
    let encrypted = cipher.update(value, 'utf8');
    encrypted = Buffer.concat([encrypted, cipher.final()]);

    console.log(base85.encode(iv) + ',' + base85.encode(encrypted));

Here `iv` works fine, but not the `encrypted` buffer. 

Note that 'ascii85' seems to work ok, but not 'z85'.

**Comment by ajmas** [comment]
Rereading the docs I now see this is a limitation of the z85 specification, though I am wondering whether throwing an exception would not be better, than returning false?

**Comment by g-enriquez** [comment]
So how can we actually make the default encode function(with z85 spec) to work?

It does return false if we run it by default, however, if we pass the ascii85 spec like:

```
base85.encode('Hello World', 'ascii85')
'<~87cURD]i,"Ebo80~>' // returns the encoded data but with ascii85 only
```

**Comment by g-enriquez** [comment]
Nvm, figured it out.

One thing to mention is that the z85 spec applied here is **different**, the string frame length specifically.

z85 spec suggests that:
> The binary frame SHALL have a length that is divisible by 4 with no remainder. The string frame SHALL have a length that is divisible by 5 with no remainder. It is up to the application to ensure that frames and strings are padded if necessary.

Hence the string 'helloworld' is encoded properly because its length = 10 % 5 = 0.
##

The default z85 spec included in this module, however, is different, it uses **4** as the divisor (which is for the binary frame length)

That's why this statement works:
```
var z85 = base85.encode('Hello, world!!!!');
console.log(z85); // nm=QNz.92Pz/PV8aT50L
```
Because 'Hello, world!!!!' length = 16 % 4 = 0
##

As mentioned in the spec, to encode the data/string, the application should ensure that the input is padded properly. In this case, we need to add a padding function to our inputs so they will work even if the string frame length is not divisible by 5.

**Comment by sigdavis** [comment]
This is super old, but I am experiencing this as well, and take it it hasn't been addressed - or a work around?

**Comment by smurfix** [comment]
I have submitted a PR that adds a `z85pad` codec without this restriction.

**Comment by noseglid** [comment]
For that use-case it would be recommended to not use z85 which has this limitation.
